### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by skyformat99**
fix Segmentation fault #758

### CODE REVIEW

**Comment by Logan007** [comment]
Thank you!!

**Comment by fengdaolong** [comment]
Why not let other operating systems other than windows use libpthread???????????????????????????????????

**Comment by Logan007** [comment]
Please see my comment over at #758. I think the underlying issue still needs some care.

**Comment by fengdaolong** [comment]
Please revert this PR and set libpthread to be disabled by default `OPTION (N2N_OPTION_USE_PTHREAD "USE PTHREAD Library" OFF)`, wait until the problem is completely resolved, and then enable libpthread by default as appropriate.

**Comment by Logan007** [comment]
> Please revert this PR and set libpthread to be disabled by default `OPTION (N2N_OPTION_USE_PTHREAD "USE PTHREAD Library" OFF)`

I will as interim. Let's discuss a sustainable solution to this over at #758.

**Pull request merged**
