### PR TITLE
Test platform macos

### PR DESCRIPTION
**Pull request by hamishcoleman**
Add macos to the auto build/tests action

### CODE REVIEW

**Comment by hamishcoleman** [comment]
I've also got a windows build, using mingw, which clearly shows some diffs in the tests-transform output - as expected from the various bug reports

**Comment by Logan007** [comment]
> I've also got a windows build, using mingw, which clearly shows some diffs in the tests-transform output - as expected from the various bug reports

I would be very interested in that. Do you want to add it to this pull request?

**Comment by hamishcoleman** [comment]
There is a bunch more hacking around to make the win32 build, so I figured on proposing the simple and working one first

That branch is a superset of this one, and is at https://github.com/hamishcoleman/n2n/tree/test_platforms

I've been able to repeat this on a win10 with git from vscode and chocolatey providing mingw and make

**Comment by hamishcoleman** [comment]
(I guess I should rewind my VM and document my local build steps)

**Comment by Logan007** [comment]
Go ahead and let me know when you are done.

**Comment by hamishcoleman** [comment]
You can see the steps I just followed to reproduce the windows/mingw build written at https://github.com/hamishcoleman/n2n/commit/d9a3e495e7464f3fca105cbb43fa6b46c7f01864

**Comment by Logan007** [comment]
Thank you.

Do you consider the MacOS part ready to be merged?

**Comment by hamishcoleman** [comment]
yeah - it didnt require any hacks and passes the test suite

**Comment by hamishcoleman** [comment]
(whereas the win32 needed me to replace autotools and port the makefiles to win32 - some of which might raise questions)

**Comment by Logan007** [comment]
> some of which might raise questions

I am curious to see...

**Pull request merged**
