### PR TITLE
Simplify the makefiles

### PR DESCRIPTION
**Pull request by hamishcoleman**

### CODE REVIEW

**Comment by fengdaolong** [comment]
I think there is no need to rename the source file.

**Comment by hamishcoleman** [comment]
The renaming is needed to reduce the number of special cases in the Makefile - if the sourcecode matches the binary then the implicit make rules can do a lot of the heavy lifting for us

**Comment by fengdaolong** [comment]
Then `CMakeLists.txt` also needs to be modified synchronously.

**Comment by hamishcoleman** [comment]
I had thought that the cmake system was deprecated, and when I noticed that it still had a CI attached to it, I did update the CMakeLists :-S

**Comment by fengdaolong** [comment]
One day in the future, we will only use CMakeLists.txt instead of Makefile to reduce the maintenance burden.

**Comment by hamishcoleman** [comment]
In the past, n2n did only use Cmake - the Makefiles and autoconf are the new make system ..

**Comment by hamishcoleman** [comment]
(besides, this is one of those vi vs emacs issues - as I use Makefiles, I can maintain them; and conversely, I found it really difficult to follow the Cmake logic when I needed to update that in the past)

**Comment by fengdaolong** [comment]
`Cmake` does have a great advantage in cross-platform compilation. If you can't choose one of the two, you can only coexist the two. The problem is that both of them need to be maintained synchronously. If one party's details are not done well, the compilation expectations may also be different.

**Comment by Logan007** [comment]
>  I found it really difficult to follow the Cmake logic when I needed to update that in the past

I can feel your pain!

> One day in the future, we will only use CMakeLists.txt instead of Makefile to reduce the maintenance burden.

While I can work with both, not really maintain neither of them, I have a slight preference towards the Makefiles...

> as I use Makefiles, I can maintain them

... so, it would be really great if you could do that!

Do you think this pull request is ready to be merged?

**Comment by hamishcoleman** [comment]
I can certainly keep looking at the Makefiles.  At the moment, I've just been shoving stuff around when it hurts - so I will keep doing that and see where we can get to.

I think this pull request is ready to be merged, yes.

**Comment by Logan007** [comment]
Thank you very much for going into the messy corners!!

**Pull request merged**
