### PR TITLE
Segmentation fault #758

### PR DESCRIPTION
**Pull request by skyformat99**
fix Segmentation fault #758

There are cases where the pointer is null.

### CODE REVIEW

**Comment by Logan007** [comment]
Thanks for diving into that. :+1:

I will have a look.

**Comment by Logan007** [comment]
Thank you!!

I have wrapped the if around the rest of the code.

**Comment by fengdaolong** [comment]
"If" statements are nested too much, it is recommended to write:
```
if(param == NULL) return ret;
```

**Comment by Logan007** [comment]
D'accord.

Readibility upgrade :wink:

**Pull request merged**
