### PR TITLE
added regular expression support

### PR DESCRIPTION
**Pull request by Logan007**
This pull request adds regular expression support to the supernode's community file intake.

Starting from #342'2 idea, this one also allows for encrypted communities by just using their name. However, the `.^$*+?[]\` are not allowed in regular community names anymore as their pure occurence is interpreted as indicator for a regular expression.

For example, a `communities` file provided to the supernode by `-c communities` with the two line

```
Logan00[0-7]'s
HQ
```

would only allow `-c Logan000\'s` … `-c Logan007\'s` (008 stays off) and ` -c HQ` at the edge.

Note that only fixed-name communities, i.e. not those defined by a regular expression, can be used with encrypted headers (`-H` at the edge). The fixed-name communities are internally marked as _non-purgeable_ so they do not get purged even if no peers are present anymore.

The `sss->lock_communities` field is more to be read as "_we do not allow any **new** communities but those that match a regular expression if given_". We still need it as it also indicates a communitywise completely free supernode if reset.

Implementation uses a new HASH_LIST of regular expressions that every newly presented community is checked against (packet handling of REGISTER_SUPER).

### CODE REVIEW

**Comment by skyformat99** [comment]
There were problems with the test.

supernode -c config.ini -l 7788 -v
file config.ini:
abc[0-9]
eee*
ddd

edge -a 10.1.0.1  -c abcef000  -k zzz  -l xx.xx.xx.xx:7788 
Expectation: Connection failed
Actual result: Successful connection

edge -a 10.1.0.1  -c ddd1 -l  xx.xx.xx.xx:7788
Expectation: Connection failed
Actual result: Successful connection

**Comment by skyformat99** [comment]
We should discuss the specific requirements:
1 When SN does not add the -c option, there is no restriction on community name.
2. When SN adds -c config-File, community name is restricted and only those that pass the filter condition can be connected.

config-file includes two format of rules:
1) abc  :  does not contain special characters, full text match, can support -H encryption.
2) fa[0-9]  :  contains special characters, regular expression filtering, does not support -H encryption.

For example, Contents of the config-file:
abc1
abc3
fa [0-9]
cnc [0-9]

So,   edge 
-c abc1    accept , Support for -H encryption
-c abc2    NG
-c abc3    accept,  Support for -H encryption
-c fa00    accept,  -H encryption is not supported
-c cnc00  accept,  -H encryption is not supported
-c cnczz   NG

**Comment by Logan007** [comment]
I am with  completely with you concerning the specs, that is exactly the way it is supposed to be. So, I guess that evaluation of matches is wrong, in `sn_utils.c`'s loop

```
HASH_ITER(hh, sss->rules, re, tmp_re) {
      allowed_match = re_matchp(re->rule, cmn.community, &match_length);
      if(allowed_match != -1)
        break;
    }
```
Is evaluation of return values from `re_matchp()` correct?

**Comment by skyformat99** [comment]
> I am with completely with you concerning the specs, that is exactly the way it is supposed to be. So, I guess that evaluation of matches is wrong, in `sn_utils.c`'s loop
> 
> ```
> HASH_ITER(hh, sss->rules, re, tmp_re) {
>       allowed_match = re_matchp(re->rule, cmn.community, &match_length);
>       if(allowed_match != -1)
>         break;
>     }
> ```
> 
> Is evaluation of return values from `re_matchp()` correct?

It should be correct, because I tested  #342.
If we all agree on this specification, 
so we only need to add the STRPBRK () function to #342 , then  support the -H encryption method.
I will try to fix it.

**Comment by Logan007** [comment]
It might be easier to adopt this PR to not store the patterns but the original strings and then use `re_match()` and not `re_matchp()` for matching. Will be slower, though (as patterns will be re-compiled every time tested).

#342 has not taken precautions against purging fixed-name communites yet.

**Comment by Logan007** [comment]
@skyformat99 

Maybe, we should take more time. I do not think it will harm to delay this feature after the release. Let us take the appropriate time to make it a clean, fast and working solution.

**Comment by skyformat99** [comment]
> @skyformat99
> 
> Maybe, we should take more time. I do not think it will harm to delay this feature after the release. Let us take the appropriate time to make it a clean, fast and working solution.

yes,That's right.
I think I've fixed the problem, and I haven't submitted PR yet.
https://github.com/skyformat99/n2n-1.git
I did a quick test , there is no problem at all,  Could you help to test it?

In fact, only  when the first time a SuperNode Register Message is sent, community name  filtering is performed,
So it doesn't affect efficiency.

**Comment by Logan007** [comment]
I am having a look at the code and will do some testing.

**Comment by Logan007** [comment]
Looking at the code (no testing yet), I have the following questions and hints:
- How will matched communities added be purged lateron? They should as supernode should handle the list of communities economically being re-ITERated all the time.
- What is the appropriate length for a regular expression in its string form?
- Performance-wise, I still am in fond of having the patterns pre-compiled to make actual matching faster. It helps scalability.
- Not sure if `num_communities` should also count the regular expressions.

However, I also took a look into the `n2n_regex.c` code to understand why the HASH_LIST of pre-compiled expressions does not seem to work in your tests. I think that I found that `n2n_regex.c` has a flaw and does not handle multiple compiles correctly due to only one static array inside the compile-function always re-using it again. It does not create per-expression instances. That is why it worked in my example (one regular expression) and did not work in your example (several regular expressions).

I would suggest that we fix `n2n_regex.c`, then #349 should be working.

**Comment by Logan007** [comment]
I think I got it working. Every expression compilation now gets its own space in memory. Also, I modified the ITERation more according to your scheme, @skyformat99, (see `match` inside the loop) because `allowed_match` alone does not neccessarily indicate a **full** match (starting position of the match == 0, could also be an infix or suffix). Thus, even though it might look odd (comparison to `-1` and to `0`, compiler will fix), I implemented it in a way one could easily remove the "full match" condition if required.

For must users, full matches might be more intuitive.

Here, all tests went smoothly.

**Comment by skyformat99** [comment]
thanks，very good
I will try test it.

**Comment by skyformat99** [comment]
file sn_utils.c 

line 819:
===================================================================================
   if (!comm) {
      HASH_ITER(hh, sss->rules, re, tmp_re) {
        allowed_match = re_matchp(re->rule, cmn.community, &match_length);

        if( (allowed_match != -1)
          && (match_length == strlen(cmn.community)) // --- only full matches allowed (remove, if also partial matches wanted)
          && (allowed_match == 0)) {                 // --- only full matches allowed (remove, if also partial matches wanted)
          match = 1;
          break;
        }
      }
    }


Should be changed to  ====>

===================================================================================
if (!comm  &&  sss->lock_communities) {
      HASH_ITER(hh, sss->rules, re, tmp_re) {
        allowed_match = re_matchp(re->rule, cmn.community, &match_length);

        if( (allowed_match != -1)
          && (match_length == strlen(cmn.community)) // --- only full matches allowed (remove, if also partial matches wanted)
          && (allowed_match == 0)) {                 // --- only full matches allowed (remove, if also partial matches wanted)
          match = 1;
          break;
        }
      }
      
      if (match !=1) { 
          return  -1;     // When the names don't match, directly return.
      }
    }

**Comment by Logan007** [comment]
I see two changes you suggest:
1. The condition of first `if (!comm && sss->lock_communities)`
2. Fast track `return`

I fully agree to number **1**. :+1: 

But I am not sure about the second one. Even though I like the idea of the fast track`return`, we should offer the code the opportunity to run until the traceEvent "unallowed community" output. I would not want to duplicate the same error-output.

Does it otherwise work well for you?

**Comment by skyformat99** [comment]
for safety, return -1 directly.
If trace is displayed, 0 will be returned.
If there is any update in the future, it is easy to introduce errors
If you want to display the trace, you can put it before return -1

**Comment by Logan007** [comment]
Hmmm, the circumstances are the same (not allowed community presented, non-matching name, neither fixed-name nor regular expression). Shouldn't the behavior be the same?

**Comment by skyformat99** [comment]
return 0 and return-1 should have different meanings.
And several places in the first half of this function are return-1.

**Comment by Logan007** [comment]
Oh, now I see what you are talking about… :facepalm:  Then, we need to change the return value in case of an unaccepted fixed-name community too. Do you see an appropriate place to do it (error message **and** return value) together for both cases – rejected fixed-name **and** regular-expressed community?

In whatever way we solve it, these two cases should go down the same path through the code. I agree that the return code should be `-1` in both cases but I am not able to see any reason why non-matching regex-communities should be treated differently from non-matching fixed-name communities.

**Comment by skyformat99** [comment]
You're right, it should return -1 if there's a mismatch (both of fix name & regex).
But your code now returns 0 in the case of a  regex  mismatch.

**Comment by Logan007** [comment]
> But your code now returns 0 in the case of a regex mismatch.

Yes, that  is the original behaviour in case of a mismatch. I think we can change it to -1.

**Comment by Logan007** [comment]
So, how about this: 

We let the code run through (no quick return) to handle it the same and do a  `return -1` right after the error message:
```
…
      traceEvent(TRACE_DEBUG, "Tx REGISTER_SUPER_ACK for %s [%s]",
                 macaddr_str(mac_buf, reg.edgeMac),
                 sock_to_cstr(sockbuf, &(ack.sock)));
    } else {
      traceEvent(TRACE_INFO, "Discarded registration: unallowed community '%s'",
                 (char*)cmn.community);
      return -1;
    }
    break;
  }
  case MSG_TYPE_QUERY_PEER: {
…
```

**Comment by skyformat99** [comment]
> So, how about this:
> 
> We let the code run through (no quick return) to handle it the same and do a `return -1` right after the error message:
> 
> ```
> …
>       traceEvent(TRACE_DEBUG, "Tx REGISTER_SUPER_ACK for %s [%s]",
>                  macaddr_str(mac_buf, reg.edgeMac),
>                  sock_to_cstr(sockbuf, &(ack.sock)));
>     } else {
>       traceEvent(TRACE_INFO, "Discarded registration: unallowed community '%s'",
>                  (char*)cmn.community);
>       return -1;
>     }
>     break;
>   }
>   case MSG_TYPE_QUERY_PEER: {
> …
> ```

Very good, thanks
My suggestion is to add return-1 in both places.
Of course, we have to respect Lucaderi's opinion in the end.

**Comment by skyformat99** [comment]
Also,  need to add a memory-free statement to the function void sn_term(n2n_sn_t *sss).
like this:
HASH_ITER(hh, sss->rules, re, tmp_re) {
    HASH_DEL(sss->rules, re);
    free(re);
  }


This statement may not be correct,  
about  re->rule = re_compile(line);    
Where is the calloc memory released?   Refer to the end of the function  re_compile().

**Comment by skyformat99** [comment]
In addition,  static int load_allowed_sn_community(n2n_sn_t *sss, char *path) ：
Add the following statement:

uint32_t num_regex = 0;

When a new regular expression exists, then
num_regex++;


At the end of the function, it should be changed to
if (num_regex>0 || num_communities>0 )
{
   sss->lock_communities = 1;
}


Otherwise, there will be a problem if the configuration file does not have any valid  line.

**Comment by Logan007** [comment]
> Also, need to add a memory-free statement to the function void sn_term(n2n_sn_t *sss)

You are right.

**Comment by Logan007** [comment]
> uint32_t num_regex = 0;

> When a new regular expression exists, then
num_regex++;

You are right. We should count them.

> At the end of the function, it should be changed to
if (num_regex>0 || num_communities>0 )
{
sss->lock_communities = 1;
}
>
> Otherwise, there will be a problem if the configuration file does not have any valid line.

That is debatable. If the user explicitly specifies `-c <file>`, she probably expects to have closed-community supernode. If there happens to be not a single valid line in that file, she should be warned. But it should not default to start up a completely free supernode – which would be completely opposite to the users's expectation in this case.

_P. S._ I just saw that invalid file will be handled returning `-1`, too, without exiting and resulting in a free supernode. I will handle it the same way (warning as a minimum, return `-1`) for now. We just need to keep in mind that the return value does not get evaluated (orderly exit on `-1` in `setOption()`? That would be different pull request…).

**Comment by Logan007** [comment]
> My suggestion is to add return-1 in both places.

I would not really care if it did not handle the very same case. But, if for any reason the error message needs to be changed or should ever additional handling be required in treating this case, it must be changed in two places.

However, you invented this feature, we do it your way!

**Comment by skyformat99** [comment]
> > My suggestion is to add return-1 in both places.
> 
> I would not really care if it did not handle the very same case. But, if for any reason the error message needs to be changed or should ever additional handling be required in treating this case, it must be changed in two places.
> 
> However, you invented this feature, we do it your way!

thanks for your work.
But it's in the wrong place.
The following code is correct: (  in the    if(!comm && sss->lock_communities) {  ....   }    )

if(!comm && sss->lock_communities) {
      HASH_ITER(hh, sss->rules, re, tmp_re) {
        allowed_match = re_matchp(re->rule, cmn.community, &match_length);

        if( (allowed_match != -1)
          && (match_length == strlen(cmn.community)) // --- only full matches allowed (remove, if also partial matches wanted)
          && (allowed_match == 0)) {                 // --- only full matches allowed (remove, if also partial matches wanted)
          match = 1;
          break;
        }
      }
      // ---- mismatch regex, return -1
      if (match != 1) {
          traceEvent(TRACE_INFO, "Discarded registration: unallowed community '%s'",
              (char*)cmn.community);
          return -1;
      }
    }


Otherwise, an error will be returned when -c conf-file  is not added.

**Comment by skyformat99** [comment]
sorry,  another error:
file sn.c  line 103  The correct one is:

if (  (num_regex + num_communities) < 1 )
  {
    traceEvent(TRACE_WARNING, "File %s does not contain any valid community names or regular expressions", path);
    return -1;
  }

**Comment by skyformat99** [comment]
The bottom one is also wrong :
HASH_ITER(hh, sss->rules, re, tmp_re) {
    HASH_DEL(sss->rules, re);
    free(re);
  }

The correct ones are shown below:

HASH_ITER(hh, sss->rules, re, tmp_re) {
    HASH_DEL(sss->rules, re);
    if (NULL!=re->rule) {
        free(re->rule);
    }
    free(re);
  }

There are two functions that need to be fix:
static int load_allowed_sn_community(n2n_sn_t *sss, char *path)  ,
void sn_term(n2n_sn_t *sss)

**Comment by Logan007** [comment]
> But it's in the wrong place.

You are right. Thank you for keeping tabs on the code!

> sorry, another error:

Okay. But I have put it yet another way.

> The bottom one is also wrong

Oh my bad… must be the weekend!

> There are two functions that need to be fix:
static int load_allowed_sn_community(n2n_sn_t *sss, char *path) ,
void sn_term(n2n_sn_t *sss)

Yes. That should be in a different pull request. ~~Maybe~~ Most probably, we will also find other parts in the code where return value handling can be done better.

**Comment by skyformat99** [comment]
Thank you for your work, this will be a perfect solution.
I will close #342 .

**Comment by lucaderi** [comment]
Thank you

**Pull request merged**
