### PR TITLE
Update edge_utils.c

### PR DESCRIPTION
**Pull request by skyformat99**
fix  compile error in Visual Studio 2015
ref  #495

### CODE REVIEW

**Comment by Logan007** [comment]
Please see my remarks over at #496.

**Comment by skyformat99** [comment]
> Please see my remarks over at #496.

ref #495,
If it is not fix, an error occurs in vs2015.
and  The fixed code  also points to the first address,  so it doesn't change the value of the expression.

**Comment by lucaderi** [comment]
I personally hate using void* and moving pointers with ++. Types should be used instead. Please rework this code

**Comment by fengdaolong** [comment]
> I personally hate using void* and moving pointers with ++. Types should be used instead. Please rework this code

I also think it should not be written like this.

Even if it is changed to `(char*)tmp_sock`, it is better than `(void*)tmp_sock`.

**Comment by Logan007** [comment]
> Even if it is changed to (char*)tmp_sock, it is better than (void*)tmp_sock.

We probably need to do that, or we need to find fully typed expression which I fear might be a bit more unreadable. Let me think. I am not sure if the code as it has changed up to now will lead to the correct addresses.

**Pull request closed without merging**
