### PR TITLE
fix register supernode loop

### PR DESCRIPTION
**Pull request by switch-st**
see issue: https://github.com/ntop/n2n/issues/341

### CODE REVIEW

**Comment by skyformat99** [comment]
sorry,  I think need to be discussed.

//  for(sn_idx=0; sn_idx<eee->conf.sn_num; sn_idx++) 
Deleting this line and maybe will cause a new bug, 

Can test it as follows:
run sn 1 on pc1 :    supernode  -l    7788
run sn 2 on pc2 :     supernode  -l    7799

then ,  
run edge1 on pc 3 :    edge  -d e1  -a 10.1.1.10  -c  zzz  -k 123  -l xx.xx.xx.xx:7788  -l xx.xx.xx.xx:7799   -v -f
run edge2 on pc 4 :    edge  -d e2  -a 10.1.1.11  -c  zzz  -k 123  -l xx.xx.xx.xx:7788  -l xx.xx.xx.xx:7799   -v -f

When killing processes in order  sn2  ,sn1,  and then start sn2 again,  
sn2 will not receive a registration message.

**Comment by switch-st** [comment]
> sorry, I think need to be discussed.
> 
> // for(sn_idx=0; sn_idxconf.sn_num; sn_idx++)
> Deleting this line and maybe will cause a new bug,
> 
> Can test it as follows:
> run sn 1 on pc1 : supernode -l 7788
> run sn 2 on pc2 : supernode -l 7799
> 
> then ,
> run edge1 on pc 3 : edge -d e1 -a 10.1.1.10 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> run edge2 on pc 4 : edge -d e2 -a 10.1.1.11 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> 
> When killing processes in order sn2 ,sn1, and then start sn2 again,
> sn2 will not receive a registration message.

I tested, and no this problem.

**Comment by switch-st** [comment]
> sorry, I think need to be discussed.
> 
> // for(sn_idx=0; sn_idxconf.sn_num; sn_idx++)
> Deleting this line and maybe will cause a new bug,
> 
> Can test it as follows:
> run sn 1 on pc1 : supernode -l 7788
> run sn 2 on pc2 : supernode -l 7799
> 
> then ,
> run edge1 on pc 3 : edge -d e1 -a 10.1.1.10 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> run edge2 on pc 4 : edge -d e2 -a 10.1.1.11 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> 
> When killing processes in order sn2 ,sn1, and then start sn2 again,
> sn2 will not receive a registration message.

I tested, and no this problem.

**Comment by switch-st** [comment]
> sorry, I think need to be discussed.
> 
> // for(sn_idx=0; sn_idxconf.sn_num; sn_idx++)
> Deleting this line and maybe will cause a new bug,
> 
> Can test it as follows:
> run sn 1 on pc1 : supernode -l 7788
> run sn 2 on pc2 : supernode -l 7799
> 
> then ,
> run edge1 on pc 3 : edge -d e1 -a 10.1.1.10 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> run edge2 on pc 4 : edge -d e2 -a 10.1.1.11 -c zzz -k 123 -l xx.xx.xx.xx:7788 -l xx.xx.xx.xx:7799 -v -f
> 
> When killing processes in order sn2 ,sn1, and then start sn2 again,
> sn2 will not receive a registration message.

I tested, and no this problem.

see this log:
image


image

**Comment by switch-st** [comment]
This code was commited here https://github.com/ntop/n2n/commit/1c7b14995b8a899ec465af3cde8228b30ed437a7 by `lucaderi`. Maybe we can solve this problem in a better way while retaining this feature.

**Comment by Logan007** [comment]
The question is: What is the intended behaviour?

Shall an edge be registered to one supernode at a time only or to all (max. two) available supernodes at the same time? As far as I can see, it _can_ only be registered to one supernode at a  time.

Does the edge tries one supernode after another? Yes, it does. 

And does it look after all supernodes? Yes, it does – over time, repeated calls of `update_supernode_reg()`. This already iterates the supenodes.

So, actually, I really am not able to see the reason for the  additional íterational `for` inside this iteration. To me, this solution still looks good (positive review). But maybe @lucaderi had another intent we have not seen yet.

@skyformat99 It could take some time (namely, the `eee->conf.register_interval` plus some `N2N_EDGE_SUP_ATTEMPTS * 0.1 * eee->conf.register_interval`) until an edge re-registers with a supernode after failure due to killed supernodes. Did you give it enough time to allow for re-registration in your setup?

**Review by Logan007 — APPROVED** [review]
Looks good to me, see my comment in Conversation section.

**Comment by switch-st** [comment]
I also tend to remove the loop code.

**Comment by skyformat99** [comment]
Provides another way to discuss which one is more appropriate.
#346

**Comment by lucaderi** [comment]
Fill use the other pull request #346

**Pull request closed without merging**
