### PR TITLE
Avoid leaking memory if the buffer is uncompressable

### PR DESCRIPTION
**Pull request by hamishcoleman**

### CODE REVIEW

**Comment by Logan007** [comment]
Good catch!

**Comment by hamishcoleman** [comment]
Ha - it wasn't hard once I noticed my resident size was in the gigs!

**Comment by Logan007** [comment]
Oh my… gigs?! Your edge must have seen a lot of throughput.

Your finding should definitely go into _dev_ branch as well.

**Comment by hamishcoleman** [comment]
Yeah, stress/stability testing with iperf3 will do that!

I had a look at dev and saw that the code had not changed, so the patch should apply cleanly

**Comment by fengdaolong** [comment]
After the compression_buffer is released, it needs to be set to null, otherwise the patch will be useless.

**Comment by fengdaolong** [comment]
After the `compression_buffer` is free, It needs to be assigned to `NULL`, otherwise the patch may be useless.

**Comment by fengdaolong** [comment]
There are many similar problems in the n2n project, which need to be dealt with one by one.

**Comment by hamishcoleman** [comment]
In this case, the variable goes out of scope immediately after the free(), so the assignment to NULL is not needed

**Pull request merged**
