### PR TITLE
Add a rendered html page to the example httpd server

### PR DESCRIPTION
**Pull request by hamishcoleman**
The httpd server now renders the data available from the json mgmt interfaces - making it a fully working demonstration

### CODE REVIEW

**Comment by Logan007** [comment]
Thank you very much!

By the way, do you mind if I rename the python files to `.py` and the shell script to `.sh`?

**Comment by hamishcoleman** [comment]
I envisioned the n2nctl script being a utility installed on the path - at which point an extension becomes annoying.  However, I would be interested to know what benefits you think come from renaming them.

Oh, I should tidy up the code lint branch a little and submit a PR - it has a little readme I wrote for the scripts dir.

**Comment by Logan007** [comment]
> I would be interested to know what benefits you think come from renaming them.

Just as indicator for the sake clarity.

> I envisioned the n2nctl script being a utility installed on the path - at which point an extension becomes annoying. 

I agree. You convinced me not to rename.

> a little readme I wrote for the scripts dir

`doc/Scripts.md`?

**Comment by hamishcoleman** [comment]
Clarity makes sense too - the `hack_fakeautoconf` script will never be an installed command (and the same for the `tools/test_harness` and the `indent` script from my lint branch)

You are right about the docs too - I'll write some more words and start a rename/cleanup/docs patch

**Comment by Logan007** [comment]
Porsche :wink:

**Comment by hamishcoleman** [comment]
With the (unplanned by me, so it didnt occur to me!) extension into semi-RESTful APIs via the management interface, I have been thinking about how to keep good REST semantics and now realise that to have a cleanly implemented and clear separation of GET (non-state-changing queries) and POST (eg a JSON equiv of +verb or stop) needs a protocol change :-(

So, I'll start adding infrastructure for that..

**Pull request merged**
