### PR TITLE
Update OpenWRT Makefile

### PR DESCRIPTION
**Pull request by VergLsm**

### CODE REVIEW

**Comment by Logan007** [comment]
Thank you!

**Comment by ghost** [comment]
Please be very careful when handling PRs from VergLsm from now on, it seemed his account might have been compromised.
He started lashing out slur in multiple issues recently, exhibiting strong desire for other people's suffering and/or willing to see others being imprisoned:
https://github.com/programthink/books/issues/100
https://github.com/programthink/zhao/issues/387
https://github.com/program-think-mirror/program-think-mirror.github.io/issues/1

**Comment by VergLsm** [comment]
> Please be very careful when handling PRs from VergLsm from now on, it seemed his account might have been compromised.
> He started lashing out slur in multiple issues recently, exhibiting strong desire for other people's suffering and/or willing to see others being imprisoned:
> [programthink/books#100](https://github.com/programthink/books/issues/100)
> [programthink/zhao#387](https://github.com/programthink/zhao/issues/387)
> [program-think-mirror/program-think-mirror.github.io#1](https://github.com/program-think-mirror/program-think-mirror.github.io/issues/1)

hhhh... 你要笑死我了，开个新号来当我的头号铁粉，针不戳，请继续你的表演，让我看看你有多能耐

**Comment by Logan007** [comment]
> his account might have been compromised.

@Plausible0Bug I agree, I have just had google translator working on that text from that previous post. Definitely not what to expect from VergLsm as we know her. Thank you for reporting!! :orange_heart:

**Comment by VergLsm** [comment]
@Logan007 My account has never been compromised. 
I am Chinese, I'm criticizing the bad guys who want to divide our country
this involves political aspects, and It's none of your business.
I know that many Chinese people are contributing to n2n,
please comment cautiously about things you don't understand

**Comment by Logan007** [comment]
@VergLsm First of all, there is no chill intended. :peace_symbol: 

As this here is definitely not the place to lead any political discussion at all, abuse was being assumed.

**Comment by VergLsm** [comment]
@Logan007 You are right, I very much agree with you
We never lead political discussions anywhere
You can see that they started the discussion first, either here or in other repository
I also hate this behavior.  Sorry for wasting your precious time

**Pull request merged**
