### PR TITLE
Fix some bugs on Windows

### PR DESCRIPTION
**Pull request by hamishcoleman**
Replacement for #1089 after I accidentally closed it

### CODE REVIEW

**Comment by Legend-Master** [comment]
I'm not sure how should I test this branch, would you mind I open another pull request from my fork's branch?

**Comment by hamishcoleman** [comment]
You can checkout this branch for testing pretty easily:

```
git checkout -b hamishcoleman-Legend-Master-dev dev
git pull git@github.com:hamishcoleman/n2n.git Legend-Master-dev
```

This branch contains the changes that I am suggesting

**Comment by Legend-Master** [comment]
Yes, I think it still works like before

**Comment by hamishcoleman** [comment]
Great!, thanks for testing

**Comment by hamishcoleman** [comment]
An unexpected side effect of the UAC prompt is that it /always/ prompts, and thus will /always/ run in a separate subshell - which makes debugging difficult and feels like a regression

**Comment by Legend-Master** [comment]
> An unexpected side effect of the UAC prompt is that it /always/ prompts, and thus will /always/ run in a separate subshell - which makes debugging difficult and feels like a regression

I'm not sure how you debug it, for me, I run vscode/visual studio in admin mode even before the change to debug it, since it won't work without admin anyway

But yeah, it's kinda bad to have it flash a console window when running in a non admin terminal and quit immediately if all you want is just showing the help message

**Pull request merged**
