### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skyformat99**
update readme.md

### CODE REVIEW

**Comment by hamishcoleman** [comment]
There is already some documentation in the doc/Building.md file - rather than making the main README.md bigger, perhaps we should remove the duplicate build details from the README file and continue to point people at the Building.md (possibly improving the Building file if needed)

**Comment by Logan007** [comment]
@hamishcoleman I agree. Also, I still prefer the makey way as default. We could add `CMake`to the enumeration of alternatives:

For Windows, MacOS, **CMake** and general building options, please check out [Building documentation](doc/Building.md) for compilation and running.

**Comment by skyformat99** [comment]
> @hamishcoleman I agree. Also, I still prefer the makey way as default. We could add `CMake`to the enumeration of alternatives:
> 
> For Windows, MacOS, **CMake** and general building options, please check out [Building documentation](doc/Building.md) for compilation and running.

ok, I agree.
close it.

**Comment by Logan007** [comment]
No need to close, we can adapt it.

**Pull request merged**
