### PR TITLE
assured correct supernode MAC address properties

### PR DESCRIPTION
**Pull request by Logan007**

### CODE REVIEW

**Comment by hamishcoleman** [comment]
Good idea.

Wont this just be surprising to those who configure their own addresses, and keep getting a different answer to the one they configured?

**Comment by Logan007** [comment]
`-m` at supernode has been enabled today so I do not expect too many users already having had used it before – especially as we did not advertise the related compile-time switch. Also, we have this filter at the edges already, more "hidden" as part of the tun_tap configuration.

**Comment by Logan007** [comment]
> Good idea.

Yeah, actually it is [yours](https://github.com/ntop/n2n/commit/89571292f4651d35e110089f7ee8c802efc96e8f#commitcomment-59108743)... Credits!!

**Comment by hamishcoleman** [comment]
Haha, nah - I was thinking of documenting or erroring, it never occured to me to simply mask the bits in/out

**Pull request merged**
