### PR TITLE
bug fix: when edge disconnects abnormally:“ERROR: authentication error, MAC or IP address already in use or not released yet by supernode”

### PR DESCRIPTION
**Pull request by dwj0**
This bug started from commit: 99b6b6b66d0785bed69cada149c0a84a3c638ebe

### CODE REVIEW

**Comment by hamishcoleman** [comment]
One of the CI tests has failed - are you able to run that test locally and confirm if you can reproduce the issue?

**Comment by dwj0** [comment]
This is the exe file of the Windows version（git dev ec15ebb80c3a656d368adf4b1b25701b8758b4f1）. Run supernode.bat and edge.bat, close edge, and then run edge.bat. At this time, "ERROR: authentication error, MAC or IP address already in use or not released yet by supernode" appears, And won't stop.
Use supernode_repair.bat to reconnect after about a minute

Of course, if edge ends with ctrl+c, it is normal
[n2n.zip](https://github.com/ntop/n2n/files/10397158/n2n.zip)

**Comment by dwj0** [comment]
In linux, use kill -9 to close edge, this problem will occur

**Comment by Logan007** [comment]
Please do not use `-9` to allow proper clean-up/sign-off at edge's end, see our [FAQ](https://github.com/ntop/n2n/blob/dev/doc/Faq.md#the-edge-repeatedly-throws-an-authentication-error-mac-or-ip-address-already-in-use-or-not-released-yet-by-supernode-message-what-is-wrong) for more details.

**Pull request closed without merging**
