### PR TITLE
revised readme and crypto docs

### PR DESCRIPTION
**Pull request by Logan007**
typos, corrections, …

### CODE REVIEW

**Comment by lucktu** [comment]
"In order to start using n2n, two elements are required:"?  I think so:
In order to start using n2n, three elements are required:
A _supernode_: it allows edge nodes to announce ...
B _edge_ nodes: the nodes which will ...
C _the third condition is that udp is allowed.

**Comment by Logan007** [comment]
With the latest commit, I have pointed to udp in one of the paragraphs.

**Comment by lucktu** [comment]
Well, that works, too.

Because some large companies or isps restrict or even prohibit udp traffic, n2n can not be used at this time.

**Comment by lucaderi** [comment]
Thanks

**Comment by Logan007** [comment]
P. S.  @lucktu In the meanwhile, as long as TCP remains unsupported, maybe [this](http://manpages.ubuntu.com/manpages/xenial/en/man1/udptunnel.1.html) kind of helper tools (and there surely are others around) might prove helpful.

**Pull request merged**
